### PR TITLE
Fix drag scrolling to work with any container

### PR DESCRIPTION
**Pull request by aminer-looker**
When dragging an element offscreen, automatically scrolling of the
viewport only happens when the root-level document is the scroll
container.  If some other element within the page is the scroll
container, no automatic scrolling occurs, and it becomes impossible
to drag a gridster item to a position offscreen.

This fix replaces the current auto-scrolling mechanism with one which
identifies the nearest scrollable container to the element being
dragged and manipulates it's scroll viewport to create the automatic
scrolling effect (falling back to the document, if necessary).

FYI—I wasn't able to run all the tests to verify the change as I don't have Selenium (and the combination of `npm` / `bower` didn't install one).  The Karma tests all passed, however.

### CODE REVIEW

**Comment by tangorri** [comment]
Goindgto test, I really hoped for this ! thanks a lot, maintainers please ?

**Comment by tangorri** [comment]
Demo show errors: 
angular-gridster.js:1472 Uncaught TypeError: $scrollContainer.height is not a function

I my app, I got:
angular-gridster.js:1485 Uncaught TypeError: Cannot read property 'top' of undefined (related again to $scrollContainer)

Do I need to specify the container and how ?

**Comment by aminer-looker** [comment]
@tangorri — Thanks for the help testing!  I've just pushed up a change which should fix the errors you were seeing.  I played around with the demo and was able to verify that it corrected at least those problems.

**Comment by tangorri** [comment]
Tested and super aprouved ! Thanks a lot @aminer-looker. I was (and may) doing my own layout engine from scratch for this feature, as I don't very read clearly this repo code.

**Comment by tangorri** [comment]
I noticed another bug
1472: Uncaught TypeError: Cannot read property 'clientHeight' of undefined

The assumed gridster based vertical scrollbar is not present (new dashboard i.e.)
I can suggest soon some code to param the container name

**Comment by tangorri** [comment]
Thanks @aminer-looker really appreciate your work. Just wondering if you can advice me how to keep the dragged widget 'centered' (or at last scroll enough to keep it visible) when I drag it outside ?

**Comment by aminer-looker** [comment]
@tangorri — I'm not entirely sure what you mean.  What I think you're saying should work automatically.  Can you explain a bit further?

**Comment by aminer-looker** [comment]
I've broken up my various independent changes into different branches.  I'm going to kill this PR and open new ones for each of those changes.

**Comment by tangorri** [comment]
ok it's closed but this is what I wanted to achieve, http://gridster.net/demos/dynamic-grid-width.html except I neeed to container to be freely layout (css is  {position: absolute; right: 300px; } in my case.).

**Pull request closed without merging**
