### PR TITLE
Performance improvement for big grids (added "sparse" flag)

### PR DESCRIPTION
**Pull request by Malczewski**
Gridster becomes very laggy, when number of rows and columns is big
(e.g. 24x100, 24 columns are required for precise resizing). With
"sparse" option enabled, it won't check all cells one by one, and will
just go through all existing items.
In my case, there was a grid with 20-25 items, size - 24x100 (default
size was 12w x 6h, i.e. 2 "columns"). Item dragging from left column to
right caused browser freezing for several seconds. With "sparse:true" it
isn't noticeable.
Second commit adds "item" into callbacks, because itemOptions contains mappings instead of numbers, when mapping object is used.

### CODE REVIEW

**Comment by danomatic** [comment]
Nice!  Is there a downside to always using sparse?  If not, can we just replace our code with yours and remove the option?

**Comment by Monyak** [comment]
It is slightly slower in cases, when most positions are filled with an item (i.e. many 1x1 items). That's why I called option "sparse" - it is much faster, if most positions are free.
But we can set sparse to true by default, because even for the worst case it will be at most 2x slower.

**Comment by pranavbhargava** [comment]
@danomatic @Malczewski This works great.. Do you think you will merge this pull request anytime soon?

**Comment by Goochie** [comment]
@pranavbhargava I agree it would be great to get this pull request merged ...

**Comment by amarkitanis** [comment]
Yes, that would be great - it should really optimise my web app!

**Comment by Malczewski** [comment]
Not sure if I did it correctly (rebase was not a good idea).

**Comment by gjungb** [comment]
+1 for this, it greatly improves the performance

**Comment by amergin** [comment]
+1

**Comment by danomatic** [comment]
I wouldn't mind a refactor that just uses this by default.  Having the grid array of arrays has a number of issues.  1 issues is that two items can't occupy the same position.  For certain layouts, it might be nice to allow two items to overlap or occupy the same row and column.  If I understand your code correctly, you are just using a single array of all items.

**Comment by gabooo** [comment]
+1 for this. I checked and with this change lots of my problems are getting solved.

**Comment by Goochie** [comment]
Again i could really do with this improvement in performance ....

**Comment by sand133** [comment]
Any news on this fix, really need it - holding me up.

**Comment by amarkitanis** [comment]
just my emails and see this is getting quite a bit of attention now, would be great if we could merge this back!

**Comment by achauve** [comment]
+1

**Comment by jocluz** [comment]
This really improves the performance!! Thank you very much! I need to have this changes because our app is not working well with big # col/rows. So I merged them to my repo and now the app works great! Thank you again!

**Comment by Deklin** [comment]
@Malczewski any chance of fixing merge conflicts to get this pr merged?

**Comment by Deklin** [comment]
@Malczewski I created a separate PR for this based on your work and it has now been merged, you can close this PR.

**Pull request closed without merging**
