### PR TITLE
Added gridster-no-drag

### PR DESCRIPTION
**Pull request by shank8**
Hey Dan,

This is my second PR. Looks like the line endings are ok now.  My work uses LF and git was configured globally to convert to LF regardless, so thats what happened.  These new files were converted to CRLF and appear to be working now.

### CODE REVIEW

**Comment by danomatic** [comment]
Can you merge latest master into your branch?  It looks like this cannot be merged without conflicts.

**Comment by danomatic** [comment]
Merged, but it won't work if you don't have jQuery loaded

**Comment by shank8** [comment]
Oh crap! didn't think about that. jqLite doesn't come with ```closest()```

**Comment by danomatic** [comment]
If it's not too much trouble that would be nice. Up to you!

**Pull request merged**
